packageExtensions:
  "cohere-ai@*":
    dependencies:
      "@aws-crypto/sha256-js": "*"
  "@llamaindex/env@*":
    dependencies:
      "@aws-crypto/sha256-js": "*"
      "pathe": "*"
      "gpt-tokenizer": "*"
  "@azure/cosmos@*":
    dependencies:
      "@azure/logger": "*"
  "bootstrap@*":
    peerDependencies:
      "@popperjs/core": "*"
  "ai@*":
    peerDependencies:
      "react": "*"
  "@llamaindex/azure@*":
    dependencies:
      "@llamaindex/core": "*"
  "@mastra/rag@*":
    dependencies:
      "llamaindex": "*"
      "@llamaindex/azure": "*"
